const SEASONS = [
  {year:2008,winner:"Rajasthan Royals",runnerUp:"Chennai Super Kings",
   orange:[{name:"Shaun Marsh",team:"KXIP",runs:616},{name:"Gautam Gambhir",team:"KKR",runs:534},{name:"Sanath Jayasuriya",team:"MI",runs:518}],
   purple:[{name:"Sohail Tanvir",team:"RR",wkts:22},{name:"Shane Warne",team:"RR",wkts:19},{name:"S. Sreesanth",team:"KXIP",wkts:19}],
   highScore:{player:"Brendon McCullum",score:"158*",team:"KKR"},
   teamHigh:{team:"CSK",score:"240/5",vs:"KXIP"},
   mvp:"Shane Watson",emerging:"Shreevats Goswami"},
  {year:2009,winner:"Deccan Chargers",runnerUp:"RCB",
   orange:[{name:"Matthew Hayden",team:"CSK",runs:572},{name:"Adam Gilchrist",team:"DC",runs:495},{name:"AB de Villiers",team:"DD",runs:465}],
   purple:[{name:"RP Singh",team:"DC",wkts:23},{name:"Anil Kumble",team:"RCB",wkts:21},{name:"Ashish Nehra",team:"DD",wkts:19}],
   highScore:{player:"Manish Pandey",score:"114*",team:"RCB"},
   teamHigh:{team:"CSK",score:"211/4",vs:"RR"},
   mvp:"Adam Gilchrist",emerging:"Rohit Sharma"},
  {year:2010,winner:"Chennai Super Kings",runnerUp:"MI",
   orange:[{name:"Sachin Tendulkar",team:"MI",runs:618},{name:"Jacques Kallis",team:"RCB",runs:572},{name:"Suresh Raina",team:"CSK",runs:520}],
   purple:[{name:"Pragyan Ojha",team:"DC",wkts:21},{name:"Amit Mishra",team:"DD",wkts:17},{name:"Harbhajan Singh",team:"MI",wkts:17}],
   highScore:{player:"Murali Vijay",score:"127",team:"CSK"},
   teamHigh:{team:"CSK",score:"246/5",vs:"RR"},
   mvp:"Sachin Tendulkar",emerging:"Saurabh Tiwary"},
  {year:2011,winner:"Chennai Super Kings",runnerUp:"RCB",
   orange:[{name:"Chris Gayle",team:"RCB",runs:608},{name:"Virat Kohli",team:"RCB",runs:557},{name:"Sachin Tendulkar",team:"MI",runs:533}],
   purple:[{name:"Lasith Malinga",team:"MI",wkts:28},{name:"Munaf Patel",team:"MI",wkts:22},{name:"Sreenath Aravind",team:"RCB",wkts:21}],
   highScore:{player:"Paul Valthaty",score:"120*",team:"KXIP"},
   teamHigh:{team:"KXIP",score:"232/2",vs:"RCB"},
   mvp:"Chris Gayle",emerging:"Iqbal Abdulla"},
  {year:2012,winner:"Kolkata Knight Riders",runnerUp:"CSK",
   orange:[{name:"Chris Gayle",team:"RCB",runs:733},{name:"Gautam Gambhir",team:"KKR",runs:590},{name:"Shikhar Dhawan",team:"DD",runs:569}],
   purple:[{name:"Morne Morkel",team:"DD",wkts:25},{name:"Sunil Narine",team:"KKR",wkts:24},{name:"Lasith Malinga",team:"MI",wkts:22}],
   highScore:{player:"Chris Gayle",score:"128*",team:"RCB"},
   teamHigh:{team:"CSK",score:"222/5",vs:"DD"},
   mvp:"Sunil Narine",emerging:"Mandeep Singh"},
  {year:2013,winner:"Mumbai Indians",runnerUp:"CSK",
   orange:[{name:"Michael Hussey",team:"CSK",runs:733},{name:"Chris Gayle",team:"RCB",runs:708},{name:"Virat Kohli",team:"RCB",runs:634}],
   purple:[{name:"Dwayne Bravo",team:"CSK",wkts:32},{name:"James Faulkner",team:"RR",wkts:28},{name:"Harbhajan Singh",team:"MI",wkts:24}],
   highScore:{player:"Chris Gayle",score:"175*",team:"RCB"},
   teamHigh:{team:"RCB",score:"263/5",vs:"PWI"},
   mvp:"Shane Watson",emerging:"Sanju Samson"},
  {year:2014,winner:"Kolkata Knight Riders",runnerUp:"KXIP",
   orange:[{name:"Robin Uthappa",team:"KKR",runs:660},{name:"Dwayne Smith",team:"CSK",runs:566},{name:"Glenn Maxwell",team:"KXIP",runs:552}],
   purple:[{name:"Mohit Sharma",team:"CSK",wkts:23},{name:"Bhuvneshwar Kumar",team:"SRH",wkts:20},{name:"Ravindra Jadeja",team:"CSK",wkts:19}],
   highScore:{player:"Virender Sehwag",score:"122",team:"KXIP"},
   teamHigh:{team:"KXIP",score:"231/4",vs:"CSK"},
   mvp:"Glenn Maxwell",emerging:"Axar Patel"},
  {year:2015,winner:"Mumbai Indians",runnerUp:"CSK",
   orange:[{name:"David Warner",team:"SRH",runs:562},{name:"Ajinkya Rahane",team:"RR",runs:540},{name:"Lendl Simmons",team:"MI",runs:540}],
   purple:[{name:"Dwayne Bravo",team:"CSK",wkts:26},{name:"Lasith Malinga",team:"MI",wkts:24},{name:"Yuzvendra Chahal",team:"RCB",wkts:23}],
   highScore:{player:"AB de Villiers",score:"133*",team:"RCB"},
   teamHigh:{team:"RCB",score:"235/1",vs:"MI"},
   mvp:"Andre Russell",emerging:"Shreyas Iyer"},
  {year:2016,winner:"Sunrisers Hyderabad",runnerUp:"RCB",
   orange:[{name:"Virat Kohli",team:"RCB",runs:973},{name:"David Warner",team:"SRH",runs:848},{name:"AB de Villiers",team:"RCB",runs:687}],
   purple:[{name:"Bhuvneshwar Kumar",team:"SRH",wkts:23},{name:"Yuzvendra Chahal",team:"RCB",wkts:21},{name:"Shane Watson",team:"RCB",wkts:20}],
   highScore:{player:"Virat Kohli",score:"113",team:"RCB"},
   teamHigh:{team:"RCB",score:"248/3",vs:"GL"},
   mvp:"Virat Kohli",emerging:"Mustafizur Rahman"},
  {year:2017,winner:"Mumbai Indians",runnerUp:"RPS",
   orange:[{name:"David Warner",team:"SRH",runs:641},{name:"Gautam Gambhir",team:"KKR",runs:498},{name:"Shikhar Dhawan",team:"SRH",runs:479}],
   purple:[{name:"Bhuvneshwar Kumar",team:"SRH",wkts:26},{name:"Jaydev Unadkat",team:"RPS",wkts:24},{name:"Jasprit Bumrah",team:"MI",wkts:20}],
   highScore:{player:"David Warner",score:"126",team:"SRH"},
   teamHigh:{team:"KXIP",score:"230/3",vs:"MI"},
   mvp:"Ben Stokes",emerging:"Basil Thampi"},
  {year:2018,winner:"Chennai Super Kings",runnerUp:"SRH",
   orange:[{name:"Kane Williamson",team:"SRH",runs:735},{name:"Rishabh Pant",team:"DD",runs:684},{name:"KL Rahul",team:"KXIP",runs:659}],
   purple:[{name:"Andrew Tye",team:"KXIP",wkts:24},{name:"Rashid Khan",team:"SRH",wkts:21},{name:"Siddarth Kaul",team:"SRH",wkts:21}],
   highScore:{player:"Rishabh Pant",score:"128*",team:"DD"},
   teamHigh:{team:"KKR",score:"245/6",vs:"KXIP"},
   mvp:"Sunil Narine",emerging:"Rishabh Pant"},
  {year:2019,winner:"Mumbai Indians",runnerUp:"CSK",
   orange:[{name:"David Warner",team:"SRH",runs:692},{name:"KL Rahul",team:"KXIP",runs:593},{name:"Quinton de Kock",team:"MI",runs:529}],
   purple:[{name:"Imran Tahir",team:"CSK",wkts:26},{name:"Kagiso Rabada",team:"DC",wkts:25},{name:"Shreyas Gopal",team:"RR",wkts:20}],
   highScore:{player:"Jonny Bairstow",score:"114",team:"SRH"},
   teamHigh:{team:"KKR",score:"232/2",vs:"MI"},
   mvp:"Andre Russell",emerging:"Shubman Gill"},
  {year:2020,winner:"Mumbai Indians",runnerUp:"DC",
   orange:[{name:"KL Rahul",team:"KXIP",runs:670},{name:"Shikhar Dhawan",team:"DC",runs:618},{name:"David Warner",team:"SRH",runs:548}],
   purple:[{name:"Kagiso Rabada",team:"DC",wkts:30},{name:"Jasprit Bumrah",team:"MI",wkts:27},{name:"Trent Boult",team:"MI",wkts:25}],
   highScore:{player:"KL Rahul",score:"132*",team:"KXIP"},
   teamHigh:{team:"RR",score:"226/6",vs:"KXIP"},
   mvp:"Jofra Archer",emerging:"Devdutt Padikkal"},
  {year:2021,winner:"Chennai Super Kings",runnerUp:"KKR",
   orange:[{name:"Ruturaj Gaikwad",team:"CSK",runs:635},{name:"Faf du Plessis",team:"CSK",runs:633},{name:"KL Rahul",team:"PBKS",runs:626}],
   purple:[{name:"Harshal Patel",team:"RCB",wkts:32},{name:"Avesh Khan",team:"DC",wkts:24},{name:"Jasprit Bumrah",team:"MI",wkts:21}],
   highScore:{player:"Jos Buttler",score:"124",team:"RR"},
   teamHigh:{team:"MI",score:"235/9",vs:"SRH"},
   mvp:"Harshal Patel",emerging:"Ruturaj Gaikwad"},
  {year:2022,winner:"Gujarat Titans",runnerUp:"RR",
   orange:[{name:"Jos Buttler",team:"RR",runs:863},{name:"KL Rahul",team:"LSG",runs:616},{name:"Quinton de Kock",team:"LSG",runs:508}],
   purple:[{name:"Yuzvendra Chahal",team:"RR",wkts:27},{name:"Wanindu Hasaranga",team:"RCB",wkts:26},{name:"Kagiso Rabada",team:"PBKS",wkts:23}],
   highScore:{player:"Quinton de Kock",score:"140*",team:"LSG"},
   teamHigh:{team:"KKR",score:"222/4",vs:"MI"},
   mvp:"Jos Buttler",emerging:"Umran Malik"},
  {year:2023,winner:"Chennai Super Kings",runnerUp:"GT",
   orange:[{name:"Shubman Gill",team:"GT",runs:890},{name:"Faf du Plessis",team:"RCB",runs:730},{name:"Devon Conway",team:"CSK",runs:672}],
   purple:[{name:"Mohammed Shami",team:"GT",wkts:28},{name:"Mohit Sharma",team:"GT",wkts:27},{name:"Rashid Khan",team:"GT",wkts:27}],
   highScore:{player:"Shubman Gill",score:"129",team:"GT"},
   teamHigh:{team:"LSG",score:"257/5",vs:"PBKS"},
   mvp:"Shubman Gill",emerging:"Yashasvi Jaiswal"},
  {year:2024,winner:"Kolkata Knight Riders",runnerUp:"SRH",
   orange:[{name:"Virat Kohli",team:"RCB",runs:741},{name:"Ruturaj Gaikwad",team:"CSK",runs:583},{name:"Riyan Parag",team:"RR",runs:573}],
   purple:[{name:"Harshal Patel",team:"PBKS",wkts:24},{name:"Varun Chakaravarthy",team:"KKR",wkts:21},{name:"T. Natarajan",team:"SRH",wkts:19}],
   highScore:{player:"Marcus Stoinis",score:"124*",team:"LSG"},
   teamHigh:{team:"SRH",score:"287/3",vs:"RCB"},
   mvp:"Sunil Narine",emerging:"Nitish Kumar Reddy"},
  {year:2025,winner:"Royal Challengers Bengaluru",runnerUp:"GT",
   orange:[{name:"Sai Sudharsan",team:"GT",runs:759},{name:"Suryakumar Yadav",team:"MI",runs:717},{name:"Virat Kohli",team:"RCB",runs:657}],
   purple:[{name:"Prasidh Krishna",team:"GT",wkts:25},{name:"Noor Ahmad",team:"GT",wkts:24},{name:"Josh Hazlewood",team:"RCB",wkts:22}],
   highScore:{player:"Abhishek Sharma",score:"141",team:"SRH"},
   teamHigh:{team:"SRH",score:"286/6",vs:"RR"},
   mvp:"Suryakumar Yadav",emerging:"Sai Sudharsan"}
];

const TEAM_COLORS = {
  "Rajasthan Royals":"#E73895","Chennai Super Kings":"#FCCA06","Deccan Chargers":"#4A4A4A",
  "RCB":"#E41E26","Mumbai Indians":"#004BA0","Kolkata Knight Riders":"#3A225D",
  "Sunrisers Hyderabad":"#FF822A","Royal Challengers Bengaluru":"#E41E26",
  "Gujarat Titans":"#1C1C2B","MI":"#004BA0","CSK":"#FCCA06","KKR":"#3A225D",
  "SRH":"#FF822A","RR":"#E73895","DC":"#4561AC","KXIP":"#ED1B24","PBKS":"#ED1B24",
  "RPS":"#6F2C91","LSG":"#00AEEF","GT":"#1C1C2B","GL":"#E04F16","PWI":"#8F63A4","DD":"#4561AC"
};

const RECORDS = [
  {icon:"🏏",label:"Highest Individual Score",value:"175*",detail:"Chris Gayle vs PWI, 2013 (66 balls, 17 sixes)"},
  {icon:"📊",label:"Most Runs in a Season",value:"973",detail:"Virat Kohli, RCB — IPL 2016"},
  {icon:"🎯",label:"Most Wickets in a Season",value:"32",detail:"Dwayne Bravo (2013) & Harshal Patel (2021)"},
  {icon:"🔥",label:"Highest Team Total",value:"287/3",detail:"SRH vs RCB — IPL 2024"},
  {icon:"💀",label:"Lowest Team Total",value:"49",detail:"RCB vs KKR — IPL 2017"},
  {icon:"🤝",label:"Highest Partnership",value:"229 runs",detail:"Kohli & de Villiers, RCB vs GL — 2016"},
  {icon:"💥",label:"Most Career Sixes",value:"357",detail:"Chris Gayle — The Universe Boss"},
  {icon:"👑",label:"Most Career Runs",value:"9,000+",detail:"Virat Kohli — Only batter to cross 9K"},
  {icon:"⚡",label:"Fastest Fifty",value:"12 balls",detail:"Chris Gayle vs PWI — 2013"},
  {icon:"🏆",label:"Most Titles",value:"6",detail:"Mumbai Indians & Chennai Super Kings"},
  {icon:"🎪",label:"Most Finals Appearances",value:"10",detail:"Chennai Super Kings"},
  {icon:"🧤",label:"Most Not Outs",value:"Record",detail:"MS Dhoni — The ultimate finisher"}
];

const FACTS = [
  {emoji:"🔁",title:"Back-to-Back Orange Caps",text:"Chris Gayle is the only player to win the Orange Cap in consecutive seasons (2011 & 2012)."},
  {emoji:"🎯",title:"Bhuvneshwar's Purple Reign",text:"Bhuvneshwar Kumar is the only bowler to win the Purple Cap in consecutive seasons (2016 & 2017)."},
  {emoji:"🌟",title:"Triple Orange Cap Club",text:"David Warner holds the record with 3 Orange Caps (2015, 2017, 2019) — the most by any player."},
  {emoji:"🧙",title:"Narine's MVP Dominance",text:"Sunil Narine has won the MVP award 3 times (2012, 2018, 2024) — the most ever, all for KKR."},
  {emoji:"🏠",title:"CSK's Fortress",text:"CSK qualified for playoffs in 12 of 17 seasons (~70%) — the highest qualification rate in IPL history."},
  {emoji:"👶",title:"Double Honours",text:"Ruturaj Gaikwad (2021) and Sai Sudharsan (2025) both won the Emerging Player Award AND Orange Cap in the same season."},
  {emoji:"🌍",title:"Only Overseas Emerging Star",text:"Mustafizur Rahman (2016, SRH) remains the only overseas player to win the Emerging Player Award."},
  {emoji:"🦁",title:"Inaugural Magic",text:"Brendon McCullum's 158* in the very first IPL match (2008) set the tone for the entire league's future."},
  {emoji:"📈",title:"The Scoring Revolution",text:"Top team totals jumped from ~240 (2008) to 287 (2024) — a 20% increase in ceiling over 16 seasons."},
  {emoji:"🏅",title:"Andre Russell's All-Round Brilliance",text:"Andre Russell won MVP twice (2015, 2019) — the only player to win it without ever winning Orange or Purple Cap."},
  {emoji:"🔮",title:"GT's Dream Debut",text:"Gujarat Titans won the title in their very first season (2022) — only the second team ever to do so after Rajasthan Royals (2008)."},
  {emoji:"💔",title:"RCB's Long Wait",text:"RCB waited 17 seasons to win their first IPL title in 2025, the longest wait by any champion."},
  {emoji:"🎓",title:"Emerging to Elite Pipeline",text:"Rohit Sharma (2009), Rishabh Pant (2018), Shubman Gill (2019), Yashasvi Jaiswal (2023) — IPL's Emerging Player Award has an elite track record of predicting India stars."},
  {emoji:"⚔️",title:"The 49 All-Out",text:"RCB were bowled out for 49 vs KKR in 2017 — still the lowest total in IPL history by a margin of 9 runs."}
];

const ANALYSIS = [
  {title:"Toss → Win Correlation",icon:"🪙",
   insight:"Teams winning the toss win ~52-55% of matches overall. But in playoffs/finals, toss winners win nearly 65% — the pressure amplifies the advantage.",
   data:[{label:"Regular Season",val:"52-55%"},{label:"Playoffs/Finals",val:"~65%"},{label:"Chase Preference",val:"Growing"}],
   conclusion:"The toss is marginally useful in league stages but becomes a significant factor in knockout matches."},
  {title:"Chase vs Defend Trend",icon:"🏃",
   insight:"The league has dramatically shifted toward chasing. Teams batting second now win 53-54% of games, driven by dew factor, target clarity, and impact player rules.",
   data:[{label:"Early Era (2008-14)",val:"~48% chase wins"},{label:"Middle Era (2015-20)",val:"~51% chase wins"},{label:"Modern Era (2021-25)",val:"~54% chase wins"}],
   conclusion:"Dew at night games + Impact Player rule has made chasing the dominant strategy — a clear causal relationship with venue conditions."},
  {title:"Scoring Inflation Over Time",icon:"📈",
   insight:"Average first-innings scores have risen ~15% since 2008. The highest team total has grown from 240 (2008) to 287 (2024). Power-hitting evolution and Impact Player rule are key drivers.",
   data:[{label:"2008 Avg 1st Innings",val:"~155"},{label:"2016 Avg 1st Innings",val:"~165"},{label:"2024 Avg 1st Innings",val:"~180"}],
   conclusion:"Bat manufacturing, fitness, T20 specialization, and the Impact Player substitution rule have caused measurable scoring inflation."},
  {title:"Orange Cap → Team Success?",icon:"🧡",
   insight:"In 18 seasons, the Orange Cap winner's team has won the title only 3 times (Tendulkar 2010, Gaikwad 2021, Sudharsan 2025). Top run-scorers rarely play for the winning team.",
   data:[{label:"Orange Cap Winner's Team Won",val:"3/18 (17%)"},{label:"Expected if random",val:"~12%"},{label:"Correlation",val:"Weak positive"}],
   conclusion:"Individual batting excellence shows only a weak correlation with team success — depth and bowling matter more."},
  {title:"Playoff Consistency by Team",icon:"🏟️",
   insight:"CSK leads with ~70% playoff qualification rate. MI and RCB follow at ~58%. Punjab Kings remain the most underperforming franchise historically.",
   data:[{label:"CSK",val:"70% (12/17)"},{label:"MI",val:"58% (11/19)"},{label:"RCB",val:"58% (11/19)"},{label:"PBKS",val:"~28% (5/18)"}],
   conclusion:"Core retention strategy and coaching stability (CSK model) shows the strongest causal link to sustained playoff success."},
  {title:"Overseas vs Indian MVP Winners",icon:"🌏",
   insight:"Of 18 MVP awards, 12 went to overseas players (67%) and only 6 to Indians. But 2 of those Indian MVPs (Tendulkar 2010, Kohli 2016) had record-breaking seasons.",
   data:[{label:"Overseas MVPs",val:"12/18 (67%)"},{label:"Indian MVPs",val:"6/18 (33%)"},{label:"Indian MVP Seasons Avg Runs",val:"795"}],
   conclusion:"Overseas all-rounders dominate the MVP metric, but when Indians win it, they tend to have historically dominant statistical seasons."}
];

const TEAM_TITLES = {"Mumbai Indians":5,"Chennai Super Kings":5,"Kolkata Knight Riders":3,"Rajasthan Royals":1,"Sunrisers Hyderabad":1,"Deccan Chargers":1,"Gujarat Titans":1,"Royal Challengers Bengaluru":1};

// Normalize team names (abbrev→canonical full name)
const TEAM_NAME_MAP = {
  "CSK":"Chennai Super Kings","Chennai Super Kings":"Chennai Super Kings",
  "MI":"Mumbai Indians","Mumbai Indians":"Mumbai Indians",
  "RCB":"Royal Challengers Bengaluru","Royal Challengers Bengaluru":"Royal Challengers Bengaluru","Royal Challengers Bangalore":"Royal Challengers Bengaluru",
  "KKR":"Kolkata Knight Riders","Kolkata Knight Riders":"Kolkata Knight Riders",
  "SRH":"Sunrisers Hyderabad","Sunrisers Hyderabad":"Sunrisers Hyderabad",
  "RR":"Rajasthan Royals","Rajasthan Royals":"Rajasthan Royals",
  "DC":"Delhi Capitals","Delhi Capitals":"Delhi Capitals","DD":"Delhi Capitals","Delhi Daredevils":"Delhi Capitals",
  "PBKS":"Punjab Kings","Punjab Kings":"Punjab Kings","KXIP":"Punjab Kings","Kings XI Punjab":"Punjab Kings",
  "GT":"Gujarat Titans","Gujarat Titans":"Gujarat Titans",
  "LSG":"Lucknow Super Giants","Lucknow Super Giants":"Lucknow Super Giants",
  "DCH":"Deccan Chargers","Deccan Chargers":"Deccan Chargers",
  "RPS":"Rising Pune Supergiant","Rising Pune Supergiant":"Rising Pune Supergiant",
  "GL":"Gujarat Lions","Gujarat Lions":"Gujarat Lions",
  "PWI":"Pune Warriors India","Pune Warriors India":"Pune Warriors India"
};

// Top 10 run-scorers per season for chart
const CHART_BATSMEN = {
  2008:[{n:"Shaun Marsh",r:616},{n:"Gautam Gambhir",r:534},{n:"Sanath Jayasuriya",r:514},{n:"Shane Watson",r:472},{n:"Graeme Smith",r:441},{n:"Adam Gilchrist",r:436},{n:"Yusuf Pathan",r:435},{n:"Suresh Raina",r:421},{n:"MS Dhoni",r:414},{n:"Virender Sehwag",r:406}],
  2009:[{n:"Matthew Hayden",r:572},{n:"Adam Gilchrist",r:495},{n:"AB de Villiers",r:465},{n:"Suresh Raina",r:434},{n:"Tillakaratne Dilshan",r:418},{n:"Jean-Paul Duminy",r:372},{n:"Herschelle Gibbs",r:371},{n:"Brad Hodge",r:365},{n:"Sachin Tendulkar",r:364},{n:"Rohit Sharma",r:362}],
  2010:[{n:"Sachin Tendulkar",r:618},{n:"Jacques Kallis",r:572},{n:"Suresh Raina",r:520},{n:"Sourav Ganguly",r:493},{n:"Murali Vijay",r:458},{n:"Mahela Jayawardene",r:439},{n:"Andrew Symonds",r:429},{n:"Saurabh Tiwary",r:419},{n:"Rohit Sharma",r:404},{n:"Naman Ojha",r:377}],
  2011:[{n:"Chris Gayle",r:608},{n:"Virat Kohli",r:557},{n:"Sachin Tendulkar",r:553},{n:"Shaun Marsh",r:504},{n:"Michael Hussey",r:492},{n:"Paul Valthaty",r:463},{n:"Suresh Raina",r:438},{n:"Murali Vijay",r:434},{n:"Virender Sehwag",r:424},{n:"Jacques Kallis",r:424}],
  2012:[{n:"Chris Gayle",r:733},{n:"Gautam Gambhir",r:590},{n:"Shikhar Dhawan",r:569},{n:"Ajinkya Rahane",r:560},{n:"Virender Sehwag",r:495},{n:"Cameron White",r:479},{n:"Rahul Dravid",r:462},{n:"Suresh Raina",r:441},{n:"Rohit Sharma",r:433},{n:"Mandeep Singh",r:432}],
  2013:[{n:"Michael Hussey",r:733},{n:"Chris Gayle",r:708},{n:"Virat Kohli",r:634},{n:"Suresh Raina",r:548},{n:"Shane Watson",r:543},{n:"Rohit Sharma",r:538},{n:"Dinesh Karthik",r:510},{n:"Ajinkya Rahane",r:488},{n:"Rahul Dravid",r:471},{n:"MS Dhoni",r:461}],
  2014:[{n:"Robin Uthappa",r:660},{n:"Dwayne Smith",r:566},{n:"Glenn Maxwell",r:552},{n:"David Warner",r:528},{n:"Suresh Raina",r:523},{n:"Virender Sehwag",r:455},{n:"David Miller",r:446},{n:"JP Duminy",r:410},{n:"Brendon McCullum",r:405},{n:"Manish Pandey",r:401}],
  2015:[{n:"David Warner",r:562},{n:"Ajinkya Rahane",r:540},{n:"Lendl Simmons",r:540},{n:"AB de Villiers",r:513},{n:"Virat Kohli",r:505},{n:"Chris Gayle",r:491},{n:"Rohit Sharma",r:482},{n:"Shreyas Iyer",r:439},{n:"Brendon McCullum",r:436},{n:"Kieron Pollard",r:419}],
  2016:[{n:"Virat Kohli",r:973},{n:"David Warner",r:848},{n:"AB de Villiers",r:687},{n:"Gautam Gambhir",r:501},{n:"Shikhar Dhawan",r:501},{n:"Rohit Sharma",r:489},{n:"Ajinkya Rahane",r:480},{n:"Murali Vijay",r:453},{n:"Quinton de Kock",r:445},{n:"Suresh Raina",r:399}],
  2017:[{n:"David Warner",r:641},{n:"Gautam Gambhir",r:498},{n:"Shikhar Dhawan",r:479},{n:"Steve Smith",r:472},{n:"Suresh Raina",r:442},{n:"Hashim Amla",r:420},{n:"Manish Pandey",r:396},{n:"Parthiv Patel",r:395},{n:"Rahul Tripathi",r:391},{n:"Robin Uthappa",r:388}],
  2018:[{n:"Kane Williamson",r:735},{n:"Rishabh Pant",r:684},{n:"KL Rahul",r:659},{n:"Ambati Rayudu",r:602},{n:"Shane Watson",r:555},{n:"Jos Buttler",r:548},{n:"Virat Kohli",r:530},{n:"Suryakumar Yadav",r:512},{n:"Dinesh Karthik",r:498},{n:"Shikhar Dhawan",r:497}],
  2019:[{n:"David Warner",r:692},{n:"KL Rahul",r:593},{n:"Quinton de Kock",r:529},{n:"Shikhar Dhawan",r:521},{n:"Andre Russell",r:510},{n:"Chris Gayle",r:490},{n:"Rishabh Pant",r:488},{n:"Virat Kohli",r:464},{n:"Shreyas Iyer",r:463},{n:"Jonny Bairstow",r:445}],
  2020:[{n:"KL Rahul",r:670},{n:"Shikhar Dhawan",r:618},{n:"David Warner",r:548},{n:"Shreyas Iyer",r:519},{n:"Ishan Kishan",r:516},{n:"Quinton de Kock",r:503},{n:"Suryakumar Yadav",r:480},{n:"Devdutt Padikkal",r:472},{n:"Virat Kohli",r:466},{n:"AB de Villiers",r:454}],
  2021:[{n:"Ruturaj Gaikwad",r:635},{n:"Faf du Plessis",r:633},{n:"KL Rahul",r:626},{n:"Shikhar Dhawan",r:587},{n:"Glenn Maxwell",r:513},{n:"Sanju Samson",r:484},{n:"Shubman Gill",r:478},{n:"Devdutt Padikkal",r:411},{n:"Virat Kohli",r:405},{n:"Prithvi Shaw",r:401}],
  2022:[{n:"Jos Buttler",r:863},{n:"KL Rahul",r:616},{n:"Quinton de Kock",r:508},{n:"David Warner",r:432},{n:"Shubman Gill",r:483},{n:"Hardik Pandya",r:487},{n:"Liam Livingstone",r:437},{n:"Faf du Plessis",r:468},{n:"Sanju Samson",r:458},{n:"Shreyas Iyer",r:401}],
  2023:[{n:"Shubman Gill",r:890},{n:"Faf du Plessis",r:730},{n:"Devon Conway",r:672},{n:"Virat Kohli",r:639},{n:"Yashasvi Jaiswal",r:625},{n:"Suryakumar Yadav",r:605},{n:"Ruturaj Gaikwad",r:590},{n:"David Warner",r:516},{n:"Rinku Singh",r:474},{n:"Ishan Kishan",r:454}],
  2024:[{n:"Virat Kohli",r:741},{n:"Ruturaj Gaikwad",r:583},{n:"Riyan Parag",r:573},{n:"Travis Head",r:567},{n:"Sanju Samson",r:531},{n:"Shubman Gill",r:527},{n:"KL Rahul",r:520},{n:"Nicholas Pooran",r:499},{n:"Sunil Narine",r:488},{n:"Abhishek Sharma",r:484}],
  2025:[{n:"Sai Sudharsan",r:759},{n:"Suryakumar Yadav",r:717},{n:"Virat Kohli",r:657},{n:"Shubman Gill",r:650},{n:"Jos Buttler",r:580},{n:"Ruturaj Gaikwad",r:545},{n:"KL Rahul",r:530},{n:"Travis Head",r:510},{n:"Abhishek Sharma",r:495},{n:"Rishabh Pant",r:480}]
};

// Top 10 wicket-takers per season for chart
const CHART_BOWLERS = {
  2008:[{n:"Sohail Tanvir",w:22},{n:"Shane Warne",w:19},{n:"S. Sreesanth",w:19},{n:"Shane Watson",w:17},{n:"Piyush Chawla",w:17},{n:"Albie Morkel",w:17},{n:"Manpreet Gony",w:17},{n:"V. Yo Mahesh",w:16},{n:"Farveez Maharoof",w:15},{n:"Irfan Pathan",w:15}],
  2009:[{n:"RP Singh",w:23},{n:"Anil Kumble",w:21},{n:"Ashish Nehra",w:19},{n:"Lasith Malinga",w:18},{n:"Irfan Pathan",w:17},{n:"Munaf Patel",w:16},{n:"Muttiah Muralitharan",w:14},{n:"Ishant Sharma",w:11},{n:"Pragyan Ojha",w:10},{n:"Zaheer Khan",w:10}],
  2010:[{n:"Pragyan Ojha",w:21},{n:"Amit Mishra",w:17},{n:"Harbhajan Singh",w:17},{n:"Anil Kumble",w:17},{n:"Vinay Kumar",w:16},{n:"Muttiah Muralitharan",w:15},{n:"Kieron Pollard",w:15},{n:"Lasith Malinga",w:15},{n:"Zaheer Khan",w:15},{n:"Irfan Pathan",w:15}],
  2011:[{n:"Lasith Malinga",w:28},{n:"Munaf Patel",w:22},{n:"Sreenath Aravind",w:21},{n:"Ravichandran Ashwin",w:20},{n:"Piyush Chawla",w:16},{n:"Ryan Harris",w:16},{n:"Chris Morris",w:15},{n:"Zaheer Khan",w:15},{n:"Dale Steyn",w:14},{n:"Dwayne Bravo",w:13}],
  2012:[{n:"Morne Morkel",w:25},{n:"Sunil Narine",w:24},{n:"Lasith Malinga",w:22},{n:"Vinay Kumar",w:19},{n:"Umesh Yadav",w:19},{n:"Dale Steyn",w:18},{n:"Parvinder Awana",w:17},{n:"Zaheer Khan",w:17},{n:"Kieron Pollard",w:16},{n:"Piyush Chawla",w:16}],
  2013:[{n:"Dwayne Bravo",w:32},{n:"James Faulkner",w:28},{n:"Harbhajan Singh",w:24},{n:"Mitchell Johnson",w:24},{n:"Vinay Kumar",w:23},{n:"Sunil Narine",w:22},{n:"Amit Mishra",w:21},{n:"Mohit Sharma",w:20},{n:"Lasith Malinga",w:20},{n:"Dale Steyn",w:19}],
  2014:[{n:"Mohit Sharma",w:23},{n:"Sunil Narine",w:21},{n:"Bhuvneshwar Kumar",w:20},{n:"Ravindra Jadeja",w:19},{n:"Sandeep Sharma",w:18},{n:"Mitchell Johnson",w:17},{n:"Axar Patel",w:17},{n:"Lasith Malinga",w:16},{n:"Varun Aaron",w:16},{n:"Ravichandran Ashwin",w:16}],
  2015:[{n:"Dwayne Bravo",w:26},{n:"Lasith Malinga",w:24},{n:"Yuzvendra Chahal",w:23},{n:"Ashish Nehra",w:22},{n:"Mitchell Starc",w:20},{n:"Imran Tahir",w:15},{n:"Andre Russell",w:14},{n:"Sunil Narine",w:14},{n:"Harbhajan Singh",w:13},{n:"Karn Sharma",w:13}],
  2016:[{n:"Bhuvneshwar Kumar",w:23},{n:"Yuzvendra Chahal",w:21},{n:"Shane Watson",w:20},{n:"Dhawal Kulkarni",w:18},{n:"Mustafizur Rahman",w:17},{n:"Mitchell McClenaghan",w:17},{n:"Dwayne Bravo",w:17},{n:"Andre Russell",w:15},{n:"Sandeep Sharma",w:15},{n:"Jasprit Bumrah",w:15}],
  2017:[{n:"Bhuvneshwar Kumar",w:26},{n:"Jaydev Unadkat",w:24},{n:"Jasprit Bumrah",w:20},{n:"Mitchell McClenaghan",w:19},{n:"Imran Tahir",w:18},{n:"Sandeep Sharma",w:17},{n:"Umesh Yadav",w:17},{n:"Rashid Khan",w:17},{n:"Pawan Negi",w:16},{n:"Axar Patel",w:15}],
  2018:[{n:"Andrew Tye",w:24},{n:"Rashid Khan",w:21},{n:"Siddarth Kaul",w:21},{n:"Umesh Yadav",w:20},{n:"Trent Boult",w:18},{n:"Hardik Pandya",w:18},{n:"Sunil Narine",w:17},{n:"Kuldeep Yadav",w:17},{n:"Shardul Thakur",w:16},{n:"Jasprit Bumrah",w:15}],
  2019:[{n:"Imran Tahir",w:26},{n:"Kagiso Rabada",w:25},{n:"Shreyas Gopal",w:20},{n:"Deepak Chahar",w:20},{n:"Khaleel Ahmed",w:19},{n:"Mohammed Shami",w:19},{n:"Yuzvendra Chahal",w:18},{n:"Rashid Khan",w:17},{n:"Jasprit Bumrah",w:17},{n:"Harbhajan Singh",w:16}],
  2020:[{n:"Kagiso Rabada",w:30},{n:"Jasprit Bumrah",w:27},{n:"Trent Boult",w:25},{n:"Anrich Nortje",w:22},{n:"Yuzvendra Chahal",w:21},{n:"Mohammed Shami",w:20},{n:"Rashid Khan",w:20},{n:"Varun Chakaravarthy",w:17},{n:"Ravichandran Ashwin",w:13},{n:"Chris Morris",w:11}],
  2021:[{n:"Harshal Patel",w:32},{n:"Avesh Khan",w:24},{n:"Jasprit Bumrah",w:21},{n:"Shardul Thakur",w:21},{n:"Rashid Khan",w:18},{n:"Rahul Chahar",w:17},{n:"Chris Morris",w:15},{n:"Yuzvendra Chahal",w:14},{n:"Deepak Chahar",w:14},{n:"Arshdeep Singh",w:13}],
  2022:[{n:"Yuzvendra Chahal",w:27},{n:"Wanindu Hasaranga",w:26},{n:"Kagiso Rabada",w:23},{n:"Umran Malik",w:22},{n:"Kuldeep Yadav",w:21},{n:"T. Natarajan",w:18},{n:"Rashid Khan",w:18},{n:"Jasprit Bumrah",w:15},{n:"Avesh Khan",w:15},{n:"Mohit Sharma",w:14}],
  2023:[{n:"Mohammed Shami",w:28},{n:"Mohit Sharma",w:27},{n:"Rashid Khan",w:27},{n:"Piyush Chawla",w:22},{n:"Arshdeep Singh",w:19},{n:"Mark Wood",w:18},{n:"Tushar Deshpande",w:17},{n:"Matheesha Pathirana",w:16},{n:"Jasprit Bumrah",w:15},{n:"Yuzvendra Chahal",w:15}],
  2024:[{n:"Harshal Patel",w:24},{n:"Varun Chakaravarthy",w:21},{n:"Jasprit Bumrah",w:20},{n:"T. Natarajan",w:19},{n:"Rashid Khan",w:17},{n:"Mustafizur Rahman",w:16},{n:"Arshdeep Singh",w:16},{n:"Kuldeep Yadav",w:15},{n:"Mohammed Siraj",w:15},{n:"Noor Ahmad",w:14}],
  2025:[{n:"Prasidh Krishna",w:25},{n:"Noor Ahmad",w:24},{n:"Josh Hazlewood",w:22},{n:"Arshdeep Singh",w:21},{n:"Jasprit Bumrah",w:20},{n:"Varun Chakaravarthy",w:19},{n:"Rashid Khan",w:18},{n:"Mohammed Shami",w:17},{n:"Trent Boult",w:16},{n:"Yuzvendra Chahal",w:15}]
};

// Top 4 playoff teams per season (1=table topper, 2-4=other qualifiers)
const CHART_TEAMS = {
  2008:["Rajasthan Royals","Chennai Super Kings","Punjab Kings","Delhi Capitals"],
  2009:["Delhi Capitals","Chennai Super Kings","Royal Challengers Bengaluru","Deccan Chargers"],
  2010:["Mumbai Indians","Deccan Chargers","Chennai Super Kings","Royal Challengers Bengaluru"],
  2011:["Royal Challengers Bengaluru","Chennai Super Kings","Mumbai Indians","Kolkata Knight Riders"],
  2012:["Delhi Capitals","Kolkata Knight Riders","Mumbai Indians","Chennai Super Kings"],
  2013:["Chennai Super Kings","Mumbai Indians","Rajasthan Royals","Sunrisers Hyderabad"],
  2014:["Punjab Kings","Kolkata Knight Riders","Chennai Super Kings","Mumbai Indians"],
  2015:["Chennai Super Kings","Mumbai Indians","Royal Challengers Bengaluru","Rajasthan Royals"],
  2016:["Gujarat Lions","Royal Challengers Bengaluru","Sunrisers Hyderabad","Kolkata Knight Riders"],
  2017:["Mumbai Indians","Rising Pune Supergiant","Sunrisers Hyderabad","Kolkata Knight Riders"],
  2018:["Sunrisers Hyderabad","Chennai Super Kings","Kolkata Knight Riders","Rajasthan Royals"],
  2019:["Mumbai Indians","Chennai Super Kings","Delhi Capitals","Sunrisers Hyderabad"],
  2020:["Mumbai Indians","Delhi Capitals","Sunrisers Hyderabad","Royal Challengers Bengaluru"],
  2021:["Delhi Capitals","Chennai Super Kings","Royal Challengers Bengaluru","Kolkata Knight Riders"],
  2022:["Gujarat Titans","Rajasthan Royals","Lucknow Super Giants","Royal Challengers Bengaluru"],
  2023:["Gujarat Titans","Chennai Super Kings","Lucknow Super Giants","Mumbai Indians"],
  2024:["Kolkata Knight Riders","Sunrisers Hyderabad","Rajasthan Royals","Royal Challengers Bengaluru"],
  2025:["Punjab Kings","Royal Challengers Bengaluru","Gujarat Titans","Mumbai Indians"]
};
